[build]
command = "npm run build"
functions = "src/lambda"
publish = "build"

[[redirects]]
from = "/graphql"
to = "/.netlify/functions/graphql"
status = 200

[[redirects]]
from = "/reviews"
to = "/.netlify/functions/reviews"
status = 200